python finetune_cyclic_lr.py clipped_data rgb 1
python finetune_cyclic_lr.py clipped_data flow 1
python finetune_cyclic_lr.py clipped_data rgb 2
python finetune_cyclic_lr.py clipped_data flow 2
python finetune_cyclic_lr.py clipped_data rgb 3
python finetune_cyclic_lr.py clipped_data flow 3
python finetune_cyclic_lr.py clipped_data rgb 4
python finetune_cyclic_lr.py clipped_data flow 4
python finetune_cyclic_lr.py clipped_data rgb 5
python finetune_cyclic_lr.py clipped_data flow 5
python finetune_cyclic_lr.py clipped_data rgb 6
python finetune_cyclic_lr.py clipped_data flow 6
python finetune_cyclic_lr.py clipped_data rgb 7
python finetune_cyclic_lr.py clipped_data flow 7
python finetune_cyclic_lr.py clipped_data rgb 8
python finetune_cyclic_lr.py clipped_data flow 8
python finetune_cyclic_lr.py clipped_data rgb 9
python finetune_cyclic_lr.py clipped_data flow 9
python finetune_cyclic_lr.py clipped_data rgb 10
python finetune_cyclic_lr.py clipped_data flow 10
python finetune_cyclic_lr.py clipped_data rgb 11
python finetune_cyclic_lr.py clipped_data flow 11
python finetune_cyclic_lr.py clipped_data rgb 12
python finetune_cyclic_lr.py clipped_data flow 12
