python ensemble.py clipped_data rgb 1
python ensemble.py clipped_data flow 1
python ensemble.py clipped_data rgb 2
python ensemble.py clipped_data flow 2
python ensemble.py clipped_data rgb 3
python ensemble.py clipped_data flow 3
python ensemble.py clipped_data rgb 4
python ensemble.py clipped_data flow 4
python ensemble.py clipped_data rgb 5
python ensemble.py clipped_data flow 5
python ensemble.py clipped_data rgb 6
python ensemble.py clipped_data flow 6
python ensemble.py clipped_data rgb 7
python ensemble.py clipped_data flow 7
python ensemble.py clipped_data rgb 8
python ensemble.py clipped_data flow 8
python ensemble.py clipped_data rgb 9
python ensemble.py clipped_data flow 9
python ensemble.py clipped_data rgb 10
python ensemble.py clipped_data flow 10
python ensemble.py clipped_data rgb 11
python ensemble.py clipped_data flow 11
python ensemble.py clipped_data rgb 12
python ensemble.py clipped_data flow 12